### ISSUE TITLE
Feed RSS errato

### ISSUE THREAD

**Issue by aborruso** [RicostruzioneTrasparente/rt-scrapers#20]
@jenkin  a riga nove [qui](http://feeds.ricostruzionetrasparente.it/albi_pretori/) c'è un `pubdate` volante e il feed [non è validato](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.ricostruzionetrasparente.it%2Falbi_pretori%2F).

Senza validazione non possiamo attivare gli automatismi con IFTTT et similia.

```
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>AlboPOP - Aggregato - </title>
<link>http://feeds.ricostruzionetrasparente.it/albi_pretori/</link>
<description>*non ufficiale* RSS feed degli Albi Pretori dei comuni italiani per </description>
<language>it</language>
<copyright>Creative Commons Attribution 4.0</copyright>
<pubDate/>
```

**Comment by jenkin** [comment]
Ok, ho fixato il pubDate volante... per l'atom:link devo [aggiornare la libreria](https://github.com/suin/php-rss-writer/commit/78f45e44a2a7cb0d82e4b9efb6f7b7a075b9051c#diff-938d6f744a90049a50c880353c6f806f).

**Comment by aborruso** [comment]
Mitico, per me conta che adesso è valido!!
