### ISSUE TITLE
Codici identificativi

### ISSUE THREAD

**Issue by aborruso** [RicostruzioneTrasparente/rt-scrapers#21]
Ciao @jenkin ,
c'è qualcosa che non mi torna.

Nell'[elenco degli albi](https://github.com/RicostruzioneTrasparente/rt-scrapers/blob/master/elenco_albi.csv), per il comune di Amandola leggo il codice `c044004`. Ma cosa è questo codice? 

Te lo chiedo perché non è né il pro_com ISTAT (per questo comune è "109002"), né il codice IPA.

Grazie

**Comment by aborruso** [comment]
@jenkin che mi dici?

**Comment by jenkin** [comment]
Credo sia il vecchio codice istat...

![screenshot_20180205_103608](https://user-images.githubusercontent.com/426495/35797580-6d007352-0a60-11e8-9a1b-6cd537b700e7.png)

**Comment by aborruso** [comment]
Ok, mi sono assegnato una issue di correzione #22
