### ISSUE TITLE
Interfaccia dello scraper

### ISSUE THREAD

**Issue by fspegni** [RicostruzioneTrasparente/rt-scrapers#3]
Salve,

contribuisco allo sviluppo di OpenMunicipio. Uno dei nostri problemi/desiderata sarebbe poter trarre vantaggio da scraper per popolare i dati degli Albi Pretori disponibili online.

Ho le seguenti domande:
- definite le specifiche di input/output che dovrebbe rispettare uno scraper?
- dalla vostra esperienza, gli Albi Pretori esportano quali atti del Comune? Solo delibere di giunta e consiglio o altro? L'elenco dei tipi di datto Puo' variare da comune a comune o c'e' uno standard/obbligo di legge che i comuni devono rispettare?
- i vs scraper esporteranno in un formato standard tutti gli atti che trovate nell'Albo Pretorio online del comune oppure solo un loro sottinsieme?
- quali e quanti formati alternativi ad Halleyweb conoscete, con cui i comuni realizzano i loro Albi Pretori?

Grazie mille per le informazioni :)

PS volevo taggare la issue con l'etichetta "domanda" ma non trovo il modo (forse non sono autorizzato)

**Comment by lorenzoperone** [comment]
> definite le specifiche di input/output che dovrebbe rispettare uno scraper?

Definiamo quelle in output dal sistema di scraping verso il sistema di acquisizione sul server

> dalla vostra esperienza, gli Albi Pretori esportano quali atti del Comune? Solo delibere di giunta e consiglio o altro?

Trovi parecchio materiale in rete come [questo](https://drive.google.com/open?id=0B70I-CmSB4Vba2xiZUR5RE5PZWs)

> L'elenco dei tipi di datto Puo' variare da comune a comune o c'e' uno standard/obbligo di legge che i comuni devono rispettare?

Vedi sopra.

> i vs scraper esporteranno in un formato standard tutti gli atti che trovate nell'Albo Pretorio online del comune oppure solo un loro sottinsieme?

Ci concentreremo sui dati della ricostruzione

> quali e quanti formati alternativi ad Halleyweb conoscete, con cui i comuni realizzano i loro Albi Pretori?

Stiamo facendo la mappatura, ci aiuti?
 
> PS volevo taggare la issue con l'etichetta "domanda" ma non trovo il modo (forse non sono autorizzato)

Vedremo di inserirla :)

**Comment by jenkin** [comment]
Le specifiche sul formato sono qui: https://github.com/RicostruzioneTrasparente/albopop-json-converter.
