### ISSUE TITLE
Tag enclosure

### ISSUE THREAD

**Issue by aborruso** [RicostruzioneTrasparente/rt-scrapers#5]
Caro @jenkin due domande.

Nel caso di più di un `enclosure`, come avete fatto sino ad ora? Ne mettere n per ogni item?

```xml
<item>
<enclosure url="http://ccc.it/1.pdf" length="[...]" type="application/pdf" />
<enclosure url="http://ccc.it/2.pdf" length="[...]" type="application/pdf" />
</item>
```

Nelle specifiche albopop `enclosure` è raccomandato. Per RT è obbligatorio immagino. Sbaglio?

Grazie

**Comment by jenkin** [comment]
Sì, ne mettiamo tanti quanto servono... anche se questo viola le specifiche RSS 2.0, che ne ammette al massimo 1. Raccomandato significa che se il dato originale esiste, deve esistere anche nel feed. Ma non è detto che esista sempre.
